### ISSUE TITLE
Run only specific flavors instead of all?

### ISSUE THREAD

**Issue by joshrlesch** [paveldudka/JacocoEverywhere#10]
Is there a way to run only a specific flavor instead of all with `connectedCheck`?

We have a Mock and Prod flavor. And I only want to run the Mock version for unit test and instrumented tests.

**Comment by paveldudka** [comment]
`connectedCheck` - is just an empty task which runs actual test tasks for all flavors.
I believe you can can be more precise with test tasks if you run flavored version:

`./gradlew connectedAndroidTestFlavorName`

So if you have `prod` & `mock` flavors, following test tasks will execute one flavor or another:

`./gradlew connectedAndroidTestProd`
`./gradlew connectedAndroidTestMock`

**Comment by joshrlesch** [comment]
Oh man, totally over looked that task in my available tasks in `./gradlew tasks`

It was `./gradlew connectedMockDebugAndroidTest` for me.

But that doesn't run both the unit tests and AndroidTests so that the code coverage for both is merged?
When I run `connectedCheck` it runs both which is what I want, but just for the Mock flavor.

Sorry kinda a noob with gradle

**Comment by paveldudka** [comment]
Oh, yeah, you'r right. Naming is wrong.
Also I forgot that there is one more task on top of test task which needs to be executed in order to generate test report.

I believe what you are looking for is:
`./gradlew createMockDebugAndroidTestCoverageReport`

It will automatically trigger `./gradlew connectedMockDebugAndroidTest` and generate test report

Not really intuitive, but should do the trick

**Comment by joshrlesch** [comment]
:boom: That worked, thank you so much, saved my day. Thanks for the plugin, its awesome!! I will close this issue.
